# Uncomment the next line to define a global platform for your project
# platform :ios, '9.1'

target 'BasicCoreML' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BasicCoreML

    pod 'Clarifai-Apple-SDK', '3.0.0-beta16'
end
